server:
  port: 81

spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 地址
    gateway:
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: loginservice
          uri: lb://loginservice
          predicates:
            - Path=/login/**