server:
  port: 81

spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      config:
        server-addr: 8.130.73.113:8848
        file-extension: yml
      discovery:
        server-addr: 8.130.73.113:8848 # nacos 地址
    gateway:
      routes:
        - id: demoservice
          uri: lb://demoservice
          predicates:
            - Path=/demoservice/**
          filters:
            - StripPrefix=1
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1
        - id: markdownservice
          uri: lb://markdownservice
          predicates:
            - Path=/markdownservice/**
          filters:
            - StripPrefix=1
        - id: esservice
          uri: lb://esservice
          predicates:
            - Path=/esservice/**
          filters:
            - StripPrefix=1