server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.61.155:3306/db?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.61.155
    port: 5672
    virtual-host: /
    username: root
    password: 1234
logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


mybatis-plus:
  configuration:
    # 将数据库中的下划线命名规则（如hotel_name）自动转换为Java类中的驼峰命名规则（如hotelName）。
    map-underscore-to-camel-case: true
  # 实体类所在的包路径
  type-aliases-package: org.example.es.hotel.pojo